# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cB0CYPBBfaVsMu3Uv1LB5P_pKR50LXcx
"""

import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("/content/DataSet_Bersih.csv")
df.head()

x = df.iloc[:,0].values
x[0:5]

y = df.iloc[:, -1].values
y[0:5]

plt.scatter(x, y)
plt.show()

"""# New Section"""